source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
inhibit_all_warnings!
project 'TimeZoneLocate'
use_frameworks!

target 'TimeZoneLocate_Example' do
  pod "TimeZoneLocate", :path => "../"
end
