source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TimeZoneLocate_Example', :exclusive => true do
  pod "TimeZoneLocate", :path => "../"
end

target 'TimeZoneLocate_Tests', :exclusive => true do
  pod "TimeZoneLocate", :path => "../"

  
end
