platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!

target 'TimeZoneLocate_Example' do
  pod 'TimeZoneLocate', :path => '../'

  target 'TimeZoneLocate_Tests' do
    inherit! :search_paths


  end
end
